### ISSUE TITLE
Batch Style Align brokes when we increase the latent image size

### ISSUE THREAD

**Issue by NeoAnthropocene** [brianfitzgerald/style_aligned_comfy#11]
Hi I tested many times and come a conclusion that we have a problem with the `StyleAligned Batch Align` node when we increase the Lantent size.

I watched videos on Youtube from a week ago and it was working before. After the last github commits we broke something here.

Here you can see the results when we increase the image size from 512 to 1024.

The image sizes are 1024x1024. This cause a problem 
![ss1](https://github.com/brianfitzgerald/style_aligned_comfy/assets/112825147/8d77af74-3510-491a-b93b-5a61cf78fc27)

512x512 image size works fine right now:
![ss2](https://github.com/brianfitzgerald/style_aligned_comfy/assets/112825147/89a6e025-71bd-4d7a-abac-76962765117f)

Workflow screen shot:
![workflow ss](https://github.com/brianfitzgerald/style_aligned_comfy/assets/112825147/eb14a0d0-1d25-408e-b155-b2cf71f84ef8)

You can DL my testing workflow to see the affects:
[Style Align workflow flaws.json](https://github.com/brianfitzgerald/style_aligned_comfy/files/14094963/Style.Align.workflow.flaws.json)

**Comment by NeoAnthropocene** [comment]
@jasonphillips would you please test the workflow in your environment?  I wonder if the problem is about the VRAM cap🤔

**Comment by jasonphillips** [comment]
I'll try later, thanks for the note. 

Based on the screenshot, I do suspect that it's something with vram limitations... it looks to me like Comfy ended up splitting your batch into 2 batches since that many images wouldn't fit into memory at once. I don't recall how it does this in practice without looking back at Comfy's code, but I'm assume they include some mechanism like this which converts a simultaneous batch into multiple batches when necessary to fit in memory. 

If that's the case, then this would be the expected outcome, because the style alignment can only work if the images are processed in memory in parallel (due to the shared attention). It won't work if the batch is actually run as multiple batches behind the scenes.

**Comment by jasonphillips** [comment]
@NeoAnthropocene 

After testing it and looking at the ComfyUI code, I can confirm my original guess:
 - ComfyUI will create batches based on available GPU memory when necessary (eg. see https://github.com/comfyanonymous/ComfyUI/blob/20e3da6b313feaac07c34a4cc746e5da931f7c76/comfy/samplers.py#L165-L171)
 - so if you exceed your max, you could end up with your batch of 10 images run as 2 batches of 5 images
 - if this happens, the Style Aligned technique won't work as expected
 
 Why? Style Aligned relies on sharing attention inside your batch, where the first image of the batch is the reference and all other images attend to that one during sampling. This means they must be sampled in memory at the same time; if your batch becomes 2 batches (so, 5 images, then 5 more images, in the case you showed), the first batch will share attention with image 1 (the diamonds in your example) and the second batch of 5 will share attention with image 6 (the mountains).

I ran your batch on a higher GPU memory (cloud GPU) and you can see that it worked normally with all 10 aligned (using SDXL in my case):
<img width="651" alt="Screenshot 2024-02-10 at 6 02 36 PM" src="https://github.com/brianfitzgerald/style_aligned_comfy/assets/5672408/dad89018-acf7-41c9-849b-97afe4c0dcef">

**However**, if you want even larger sets of aligned images without the requirement of fitting it all into memory in one batch, you have another easy option.

Simply repeat your seed, and keep the first image prompt in the batch -- but change all the others. Now, you'll get a new batch of images that shares attention with the same reference as your previous batch. 

See my example below of doing this with your workflow; I simply changed prompts 1-9 and let prompt 0 the same with the same seed. You can see that my new batch of images shares style with my previous batch above.
<img width="667" alt="Screenshot 2024-02-10 at 6 05 58 PM" src="https://github.com/brianfitzgerald/style_aligned_comfy/assets/5672408/f07da230-1338-48f8-b4fb-8e7a9fc1da55">

**Comment by NeoAnthropocene** [comment]
@jasonphillips I understand. 

Could you consider adding a "Low VRAM" or "Distributed Render" option to the class? 
This would process batches sequentially, taking the first image and then moving to the next. This way, even users with 8GB of VRAM could achieve consistent style transfer results. 

While I can easily use the auxiliary method you suggested, this option would be a great help to those with limited VRAM. Additionally, it could allow for higher-resolution processing.

**Comment by NeoAnthropocene** [comment]
I'm closing this thread and going to open a feature request for the [above](https://github.com/brianfitzgerald/style_aligned_comfy/issues/11#issuecomment-1968477854) request :)

THanks again for the help 👍🏻
